name: Code Checks
on: push
jobs:

  test-python-3-10:
    name: Check Python ${{ matrix.python-version }} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # OS Hidden: Really a 2x2 matrix with Ubuntu on second row
        python-version: ["3.10","3.11"]
    steps:
      # Actions are github's predefined task
      # View on https://github.com/marketplace/actions/checkout
      # @vX uses version X of the action
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
      
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: python -m pip install -e .[test]

      - name: Test package
        run: python -m pytest